Repository Stack101/stack101-frontend, pull requests merged in 2020-05, with the labels that each got.

#9 Fixup/sync up
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/api/stack.api.js
  src/assets/styles/index.scss
  src/components/blocks/search-form/SearchForm.vue
  src/components/blocks/stack-bar-chart/StackBarChart.vue
  src/components/blocks/stack-toggle-tab/StackToggleTab.vue
  src/components/elements/AppButton.vue
  src/components/layout/app-header/AppHeader.vue
  src/components/layout/search-header/SearchHeader.vue
  src/components/layout/statistic-info/StatisticInfo.vue
  src/mockData.js
  src/router/index.js
  src/store/modules/stack.store.js
  src/store/modules/statistic.store.js
  src/views/AppMain.vue
  src/views/AppSearch.vue
Labels: develop

#16 [UPDATE]--폰트 import url 적용(임시)
  src/assets/styles/base/_reset.scss
  src/assets/styles/index.scss
  src/assets/styles/utils/variables/_font.scss
Labels: develop

#17 Feature/stack info filter #14
  src/assets/images/icon_down_arrow_512x512.png
  src/components/blocks/stack-filter-dropdown/StackFilterDropdown.vue
  src/components/blocks/stack-filter-list/StackFilterList.vue
  src/components/blocks/stack-result/StackResult.vue
  src/components/elements/AppButton.vue
  src/components/layout/stack-info/StackInfo.vue
Labels: develop

#18 Feature/favorite
  src/api/index.js
  src/components/blocks/bookmark-tab/BookmarkTab.vue
  src/components/elements/AppText.vue
  src/components/layout/main-header/MainHeader.vue
  src/router/index.js
  src/views/AppBookmark.vue
Labels: develop

#22 Fixup/api connection company detail
  .eslintrc.js
  src/api/company.api.js
  src/components/blocks/company-stack-form/CompanyStackForm.vue
  src/components/blocks/stack-toggle-bar/StackToggleBar.vue
  src/components/layout/company-stack-list/CompanyStackList.vue
  src/views/AppDetailCompany.vue
Labels: develop

#27 [UPDATE]--API 반환값 스펠링 변경에 따른 프론트엔드 값 수정
  src/components/blocks/stack-filter-list/StackFilterList.vue
  src/components/blocks/stack-toggle-tab/StackToggleTab.vue
  src/components/layout/company-stack-list/CompanyStackList.vue
  src/components/layout/stack-info/StackInfo.vue
  src/components/layout/statistic-info/StatisticInfo.vue
  src/components/layout/statistic-info/statisticColors.js
  src/views/AppDetailCompany.vue
Labels: develop

#28 [STYLE]--서치 헤더 해상도에 따른 취소 버튼 짤림 문제 수정
  src/components/blocks/search-form/SearchForm.vue
  src/components/layout/search-header/SearchHeader.vue
Labels: bug

#30 Fixup/api call
  src/api/stack.api.js
  src/components/layout/detail-info/DetailInfo.vue
  src/components/layout/stack-info/StackInfo.vue
  src/store/modules/company.store.js
  src/store/modules/stack.store.js
  src/views/AppDetailCompany.vue
  src/views/AppDetailStack.vue
Labels: update

#31 [UPDATE]--eslint-console-error-off
  .eslintrc.js
Labels: bug, update
